[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/deals"
  to = "/.netlify/functions/get-deals"
  status = 200

[[redirects]]
  from = "/go"
  to = "/.netlify/functions/go"
  status = 200
