[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/deals"
  to = "/.netlify/functions/get-deals"
  status = 200

[[redirects]]
  // FROM:
schedule: "0 * * * *",

// TO:
schedule: "*/10 * * * *",
