import AsyncStorage from '@react-native-async-storage/async-storage';
import { useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { colors } from '@/constants/colors';
import { useProfile } from '@/context/profile-context';
import { disableAlerts, getPushToken, saveAlertPreferences } from '@/services/alerts';

const KEY = 'deals-aholic:alert-preferences';
const popular = [['Laptop', '💻'], ['Nike', '👟'], ['Apple', '🍎'], ['TV', '📺'], ['LEGO', '🧱'], ['Tablet', '📱'], ['Nintendo Switch', '🎮']] as const;
const categories = ['Electronics', 'Fashion', 'Home', 'Beauty', 'Toys', 'Pets', 'Sports'];

export default function AlertsScreen() {
  const { profile } = useProfile();
  const [tab, setTab] = useState<'alerts' | 'notifications'>('alerts');
  const [input, setInput] = useState(''); const [keywords, setKeywords] = useState<string[]>([]); const [selected, setSelected] = useState<string[]>([]); const [featured, setFeatured] = useState(false); const [enabled, setEnabled] = useState(false); const [saving, setSaving] = useState(false);
  useEffect(() => { AsyncStorage.getItem(KEY).then((saved) => { if (!saved) return; const value = JSON.parse(saved); setKeywords(value.keywords || []); setSelected(value.categories || []); setFeatured(Boolean(value.featured)); setEnabled(Boolean(value.enabled)); }).catch(() => undefined); }, []);
  const allCategories = useMemo(() => featured ? [...selected, 'featured'] : selected, [featured, selected]);
  const add = (value = input) => { const term = value.trim(); if (!term) return; setKeywords((items) => items.some((item) => item.toLowerCase() === term.toLowerCase()) ? items : [...items, term]); setInput(''); };
  const save = async () => {
    if (!profile) return Alert.alert('Join the community first', 'Create a profile or continue as a guest in Profile before turning on alerts.');
    const finalKeywords = input.trim() && !keywords.some((item) => item.toLowerCase() === input.trim().toLowerCase()) ? [...keywords, input.trim()] : keywords;
    if (!finalKeywords.length && !allCategories.length) return Alert.alert('Choose an alert', 'Add a keyword, popular alert, category, or Deal of the Day.');
    setSaving(true); try { const token = await getPushToken(); await saveAlertPreferences(profile, token, finalKeywords, allCategories.map((item) => item.toLowerCase())); setKeywords(finalKeywords); setInput(''); await AsyncStorage.setItem(KEY, JSON.stringify({ keywords: finalKeywords, categories: selected, featured, enabled: true })); setEnabled(true); Alert.alert('Deal alerts are on', 'We will notify you when a new matching deal appears.'); } catch (error) { Alert.alert('Could not enable alerts', error instanceof Error ? error.message : 'Please try again.'); } finally { setSaving(false); }
  };
  const off = async () => { if (!profile) return; setSaving(true); try { await disableAlerts(profile); await AsyncStorage.setItem(KEY, JSON.stringify({ keywords, categories: selected, featured, enabled: false })); setEnabled(false); } finally { setSaving(false); } };
  if (tab === 'notifications') return <ScrollView contentContainerStyle={styles.content}><Title tab={tab} setTab={setTab} /><View style={styles.notice}><Text style={styles.noticeIcon}>{enabled ? '🔔' : '🔕'}</Text><Text style={styles.noticeTitle}>{enabled ? 'Your deal alerts are active' : 'No alerts yet'}</Text><Text style={styles.noticeCopy}>{enabled ? 'New matching deals will appear in your phone notifications.' : 'Create a deal alert and we will notify you when a matching deal drops.'}</Text>{!enabled && <Pressable style={styles.blueButton} onPress={() => setTab('alerts')}><Text style={styles.blueText}>Browse Deal Alerts</Text></Pressable>}</View></ScrollView>;
  return <ScrollView contentContainerStyle={styles.content}>
    <Title tab={tab} setTab={setTab} />
    <View style={styles.hero}><Text style={styles.heroTitle}>Don’t miss out</Text><Text style={styles.heroCopy}>Get notified when great deals drop.</Text><View style={styles.searchWrap}><TextInput value={input} onChangeText={setInput} onSubmitEditing={() => add()} placeholder="Add keywords, stores, brands…" placeholderTextColor="#777" style={styles.search} /><Pressable style={styles.searchAdd} onPress={() => add()}><Text style={styles.searchAddText}>＋</Text></Pressable></View></View>
    {!!keywords.length && <View style={styles.pills}>{keywords.map((item) => <Pressable key={item} style={styles.pill} onPress={() => setKeywords((items) => items.filter((entry) => entry !== item))}><Text style={styles.pillText}>{item} ×</Text></Pressable>)}</View>}
    <Text style={styles.sectionTitle}>Popular Alerts</Text><View style={styles.card}>{popular.map(([name, icon], index) => { const added = keywords.some((item) => item.toLowerCase() === name.toLowerCase()); return <View key={name} style={[styles.row, index === popular.length - 1 && styles.last]}><View style={styles.icon}><Text>{icon}</Text></View><Text style={styles.rowName}>{name}</Text><Pressable style={[styles.add, added && styles.added]} onPress={() => added ? setKeywords((items) => items.filter((item) => item.toLowerCase() !== name.toLowerCase())) : add(name)}><Text style={styles.addText}>{added ? 'Added ✓' : 'Add  +'}</Text></Pressable></View>; })}</View>
    <Text style={styles.sectionTitle}>Browse by category</Text><View style={styles.chips}>{categories.map((item) => <Pressable key={item} onPress={() => setSelected((items) => items.includes(item) ? items.filter((entry) => entry !== item) : [...items, item])} style={[styles.chip, selected.includes(item) && styles.chipActive]}><Text style={[styles.chipText, selected.includes(item) && styles.chipTextActive]}>{item}</Text></Pressable>)}</View>
    <Pressable style={[styles.featured, featured && styles.featuredActive]} onPress={() => setFeatured((value) => !value)}><Text style={styles.featuredEmoji}>🔥</Text><Text style={styles.featuredTitle}>Deal of the Day</Text><Text style={styles.featuredCopy}>Get alerts on our hottest featured deals.</Text><Text style={styles.featuredAdd}>{featured ? 'Added ✓' : 'Add  +'}</Text></Pressable>
    <Pressable style={[styles.blueButton, saving && styles.dim]} disabled={saving} onPress={save}><Text style={styles.blueText}>{saving ? 'Saving…' : enabled ? 'Update deal alerts' : 'Turn on deal alerts'}</Text></Pressable>{enabled && <Pressable style={styles.off} disabled={saving} onPress={off}><Text style={styles.offText}>Turn off alerts</Text></Pressable>}<Text style={styles.note}>Tap a selected alert to remove it. We only send alerts for new matching deals.</Text>
  </ScrollView>;
}

function Title({ tab, setTab }: { tab: 'alerts' | 'notifications'; setTab: (value: 'alerts' | 'notifications') => void }) { return <><Text style={styles.title}>Alerts</Text><View style={styles.segment}><Pressable style={[styles.segmentButton, tab === 'alerts' && styles.segmentActive]} onPress={() => setTab('alerts')}><Text style={styles.segmentText}>Deal Alerts</Text></Pressable><Pressable style={[styles.segmentButton, tab === 'notifications' && styles.segmentActive]} onPress={() => setTab('notifications')}><Text style={styles.segmentText}>Notifications</Text></Pressable></View></>; }

const styles = StyleSheet.create({
  content: { paddingBottom: 42, backgroundColor: '#fff', flexGrow: 1 }, title: { color: '#111', fontSize: 29, textAlign: 'center', fontWeight: '900', marginTop: 18, marginBottom: 16 }, segment: { height: 52, flexDirection: 'row', marginHorizontal: 18, padding: 3, borderRadius: 28, backgroundColor: '#ECECEC' }, segmentButton: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: 24 }, segmentActive: { backgroundColor: '#fff', shadowColor: '#777', shadowOpacity: 0.16, shadowRadius: 4, shadowOffset: { width: 0, height: 1 } }, segmentText: { color: '#222', fontSize: 16, fontWeight: '800' },
  hero: { marginTop: 22, padding: 25, backgroundColor: '#FFE0A8' }, heroTitle: { color: '#111', fontSize: 30, textAlign: 'center', fontWeight: '900' }, heroCopy: { color: '#4B4B4B', fontSize: 18, textAlign: 'center', marginTop: 5 }, searchWrap: { minHeight: 54, marginTop: 21, paddingLeft: 18, borderRadius: 28, flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff' }, search: { flex: 1, color: '#111', fontSize: 15 }, searchAdd: { width: 48, alignItems: 'center' }, searchAddText: { color: '#111', fontSize: 28, fontWeight: '500' },
  pills: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, paddingHorizontal: 18, paddingTop: 14 }, pill: { paddingHorizontal: 11, paddingVertical: 7, borderRadius: 17, backgroundColor: '#E8F2FF' }, pillText: { color: '#1264CE', fontSize: 12, fontWeight: '800' }, sectionTitle: { color: '#333', fontSize: 27, fontWeight: '900', marginHorizontal: 18, marginTop: 25, marginBottom: 13 }, card: { overflow: 'hidden', marginHorizontal: 18, borderRadius: 17, backgroundColor: '#F6F6F6' }, row: { minHeight: 75, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#E5E5E5' }, last: { borderBottomWidth: 0 }, icon: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff', borderWidth: 1, borderColor: '#E6E6E6' }, rowName: { flex: 1, marginLeft: 13, color: '#191919', fontSize: 19, fontWeight: '600' }, add: { minWidth: 80, minHeight: 38, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff', borderWidth: 1, borderColor: '#D4D4D4' }, added: { backgroundColor: '#E8F7EF', borderColor: '#A8DDBB' }, addText: { color: '#111', fontSize: 13, fontWeight: '900' },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, paddingHorizontal: 18 }, chip: { paddingHorizontal: 13, paddingVertical: 9, borderRadius: 18, backgroundColor: '#F3F3F3' }, chipActive: { backgroundColor: '#1D6FEA' }, chipText: { color: '#333', fontSize: 12, fontWeight: '800' }, chipTextActive: { color: '#fff' }, featured: { minHeight: 150, alignItems: 'center', margin: 18, padding: 18, borderRadius: 18, backgroundColor: '#E6D9FF' }, featuredActive: { borderWidth: 2, borderColor: '#1D6FEA' }, featuredEmoji: { fontSize: 29 }, featuredTitle: { color: '#111', fontSize: 24, fontWeight: '900', marginTop: 5 }, featuredCopy: { color: '#393939', fontSize: 13, marginTop: 3 }, featuredAdd: { marginTop: 13, paddingHorizontal: 17, paddingVertical: 9, borderRadius: 20, color: '#111', backgroundColor: '#fff', fontSize: 13, fontWeight: '900' },
  blueButton: { minHeight: 55, alignItems: 'center', justifyContent: 'center', marginHorizontal: 18, borderRadius: 28, backgroundColor: '#1D6FEA' }, blueText: { color: '#fff', fontSize: 16, fontWeight: '900' }, off: { minHeight: 45, alignItems: 'center', justifyContent: 'center', marginTop: 6 }, offText: { color: colors.red, fontSize: 13, fontWeight: '900' }, note: { color: '#777', fontSize: 11, lineHeight: 17, textAlign: 'center', paddingHorizontal: 28, marginTop: 13 }, dim: { opacity: 0.6 }, notice: { margin: 22, padding: 25, borderRadius: 20, alignItems: 'center', backgroundColor: '#F6F6F6' }, noticeIcon: { fontSize: 38 }, noticeTitle: { color: '#111', fontSize: 23, textAlign: 'center', fontWeight: '900', marginTop: 10 }, noticeCopy: { color: '#666', fontSize: 15, lineHeight: 22, textAlign: 'center', marginTop: 9 },
});
